{{- with .Values.prometheus.serviceMonitor }}
{{- if .create -}}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "authentik.names.fullname" $ }}
  labels:
    {{- include "authentik.labels" $ | nindent 4 }}
    {{- with .labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  endpoints:
    - port: http-metrics
      scrapeTimeout: {{ .scrapeTimeout }}
      interval: {{ .interval }}
  selector:
    matchLabels:
      {{- include "authentik.labels.selectorLabels" $ | nindent 6 }}
{{- end }}
{{- end }}
