apiVersion: v1
kind: Secret
metadata:
  name: {{ include "authentik.names.fullname" $ }}
  labels:
    {{- include "authentik.labels" $ | nindent 4 }}
  annotations:
    {{/* Since we need the secret for the migration job, it technically needs to be a hook with less priority than the job */}}
    helm.sh/hook: pre-install,pre-upgrade
    helm.sh/hook-weight: "-5"
    helm.sh/resource-policy: keep
  {{- if $.Values.annotations }}
    {{- toYaml $.Values.annotations | nindent 4 }}
  {{- end }}
data:
  {{- include "authentik.env" (dict "root" $ "values" $.Values.authentik) | indent 2 }}
  {{- if $.Values.geoip.enabled }}
  GEOIPUPDATE_ACCOUNT_ID: {{ required "geoip account id required" $.Values.geoip.accountId | b64enc | quote }}
  GEOIPUPDATE_LICENSE_KEY: {{ required "geoip license key required" $.Values.geoip.licenseKey | b64enc | quote }}
  {{- end }}
