apiVersion: v1
kind: Secret
metadata:
  name: {{ include "authentik.names.fullname" $ }}
  labels:
    {{- include "authentik.labels" $ | nindent 4 }}
  {{- if $.Values.annotations }}
  annotations:
    {{- toYaml $.Values.annotations | nindent 4 }}
  {{- end }}
data:
  {{- include "authentik.env" (dict "root" $ "values" $.Values.authentik) | indent 2 }}
  {{- if $.Values.geoip.enabled }}
  GEOIPUPDATE_ACCOUNT_ID: {{ required "geoip account id required" $.Values.geoip.accountId | b64enc | quote }}
  GEOIPUPDATE_LICENSE_KEY: {{ required "geoip license key required" $.Values.geoip.licenseKey | b64enc | quote }}
  {{- end }}
