{{- if .Values.authentik.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "authentik.fullname" . }}
  namespace: {{ include "authentik.namespace" . | quote }}
  labels:
    {{- include "authentik.labels" (dict "context" .) | nindent 4 }}
  {{- if .Values.global.secretAnnotations }}
  annotations:
    {{- toYaml .Values.global.secretAnnotations | nindent 4 }}
  {{- end }}
data:
  {{- include "authentik.env" (dict "root" . "values" .Values.authentik) | indent 2 }}
  {{- if and .Values.geoip.enabled (not .Values.geoip.existingSecret.secretName) }}
  GEOIPUPDATE_ACCOUNT_ID: {{ required "geoip account id required" .Values.geoip.accountId | b64enc | quote }}
  GEOIPUPDATE_LICENSE_KEY: {{ required "geoip license key required" .Values.geoip.licenseKey | b64enc | quote }}
  {{- end }}
{{- end }}
