{{- if .Values.pdb.server.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ printf "%s-%s" (include "authentik.names.fullname" $) "server" }}
  labels:
    {{- include "authentik.labels" $ | nindent 4 }}
    app.kubernetes.io/component: "server"
    {{- with $.Values.pdb.server.labels }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
  annotations:
    {{- toYaml $.Values.pdb.server.annotations | nindent 4 }}
spec:
  {{- with $.Values.pdb.server.maxUnavailable }}
  maxUnavailable: {{ . }}
  {{- else }}
  minAvailable: {{ $.Values.pdb.server.minAvailable | default 0 }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "authentik.labels" $ | nindent 6 }}
      app.kubernetes.io/component: server
{{- end }}
