---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ printf "%s-%s" (include "authentik.names.fullname" $) "worker" }}
  labels:
    {{- include "authentik.labels" $ | nindent 4 }}
    app.kubernetes.io/component: "worker"
  {{- if $.Values.annotations }}
  annotations:
    {{- toYaml $.Values.annotations | nindent 4 }}
  {{- end }}
spec:
  {{- if not $.Values.autoscaling.worker.enabled }}
  replicas: {{ $.Values.worker.replicas }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "authentik.labels.selectorLabels" $ | nindent 6 }}
      app.kubernetes.io/component: "worker"
  template:
    metadata:
      labels:
        {{- include "authentik.labels.selectorLabels" $ | nindent 8 }}
        app.kubernetes.io/component: "worker"
        app.kubernetes.io/version: "{{ trunc 63 $.Values.image.tag }}"
      annotations:
        goauthentik.io/config-checksum: {{ include (print $.Template.BasePath "/secret.yaml") . | sha256sum }}
      {{- if $.Values.podAnnotations }}
        {{- toYaml $.Values.podAnnotations | nindent 8 }}
      {{- end }}
    spec:
      {{- if $.Values.image.pullSecrets }}
      imagePullSecrets:
        {{- toYaml $.Values.image.pullSecrets | nindent 8 }}
      {{- end }}
      {{- if $.Values.serviceAccount.create }}
      serviceAccountName: {{ include "authentik-remote-cluster.fullname" .Subcharts.serviceAccount }}
      {{- end }}
      {{- with $.Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with $.Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with $.Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      enableServiceLinks: true
      {{- if $.Values.initContainers }}
      initContainers:
        {{- $initContainers := list }}
        {{- range $index, $key := (keys $.Values.initContainers | uniq | sortAlpha) }}
          {{- $container := get $.Values.initContainers $key }}
          {{- if not $container.name -}}
            {{- $_ := set $container "name" $key }}
          {{- end }}
          {{- $initContainers = append $initContainers $container }}
        {{- end }}
        {{- tpl (toYaml $initContainers) $ | nindent 8 }}
      {{- end }}
      {{- if $.Values.worker.priorityClassName }}
      priorityClassName: {{ $.Values.worker.priorityClassName }}
      {{- end }}
      securityContext:
        {{- toYaml $.Values.worker.securityContext | nindent 8 }}
      containers:
        - name: {{ $.Chart.Name }}
          image: "{{ $.Values.image.repository }}:{{ $.Values.image.tag }}{{- if $.Values.image.digest -}}@{{ $.Values.image.digest }}{{- end -}}"
          imagePullPolicy: "{{ $.Values.image.pullPolicy }}"
          args: ["worker"]
          env:
            {{- range $k, $v := $.Values.env }}
            - name: {{ quote $k }}
              value: {{ quote $v }}
            {{- end }}
            {{- range $name, $val := $.Values.envValueFrom }}
            - name: {{ $name }}
              valueFrom:
                {{- toYaml $val | nindent 16 }}
            {{- end }}
          envFrom:
            - secretRef:
                name: {{ include "authentik.names.fullname" $ }}
            {{- with $.Values.envFrom }}
              {{- toYaml . | nindent 12 }}
            {{- end }}
          volumeMounts:
          {{- if $.Values.geoip.enabled }}
            - name: geoip-db
              mountPath: /geoip
          {{- end }}
            {{- with $.Values.volumeMounts }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
            {{- with $.Values.blueprints }}
              {{- range $name := . }}
            - name: blueprints-{{ $name }}
              mountPath: /blueprints/mounted/{{ $name }}
              {{- end }}
            {{- end }}
            {{- with index $.Values.resources "worker" }}
          resources:
              {{- toYaml . | nindent 12 }}
            {{- end }}
          securityContext:
            {{- toYaml $.Values.worker.containerSecurityContext | nindent 12 }}
      {{- if $.Values.geoip.enabled }}
        - name: geoip-sidecar
          image: "{{ $.Values.geoip.image }}"
          env:
            - name: GEOIPUPDATE_FREQUENCY
              value: {{ $.Values.geoip.updateInterval | quote }}
            - name: GEOIPUPDATE_PRESERVE_FILE_TIMES
              value: "1"
            - name: GEOIPUPDATE_ACCOUNT_ID
              valueFrom:
                secretKeyRef:
                  name: {{ include "authentik.names.fullname" $ }}
                  key: GEOIPUPDATE_ACCOUNT_ID
            - name: GEOIPUPDATE_LICENSE_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ include "authentik.names.fullname" $ }}
                  key: GEOIPUPDATE_LICENSE_KEY
            - name: GEOIPUPDATE_EDITION_IDS
              value: {{ required "geoip edition id required" $.Values.geoip.editionIds | quote }}
          volumeMounts:
            - name: geoip-db
              mountPath: /usr/share/GeoIP
          securityContext:
            {{- toYaml $.Values.geoip.containerSecurityContext | nindent 12 }}
      {{- end }}
      {{- with $.Values.additionalContainers }}
        {{- $additionalContainers := list }}
        {{- range $name, $container := . }}
          {{- if not $container.name -}}
            {{- $_ := set $container "name" $name }}
          {{- end }}
          {{- $additionalContainers = append $additionalContainers $container }}
        {{- end }}
        {{- tpl (toYaml $additionalContainers) $ | nindent 8 }}
      {{- end }}
      volumes:
      {{- if $.Values.geoip.enabled }}
        - name: geoip-db
          emptyDir: {}
      {{- end }}
      {{- with $.Values.volumes }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with $.Values.blueprints }}
        {{- range $name := . }}
        - name: blueprints-{{ $name }}
          configMap:
            name: {{ $name }}
        {{- end }}
      {{- end }}
