{{- if .Values.pdb.worker.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ printf "%s-%s" (include "authentik.names.fullname" $) "worker" }}
  labels:
    {{- include "authentik.labels" $ | nindent 4 }}
    app.kubernetes.io/component: "worker"
    {{- with $.Values.pdb.worker.labels }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
  annotations:
    {{- toYaml $.Values.pdb.worker.annotations | nindent 4 }}
spec:
  {{- with $.Values.pdb.worker.maxUnavailable }}
  maxUnavailable: {{ . }}
  {{- else }}
  minAvailable: {{ $.Values.pdb.worker.minAvailable | default 0 }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "authentik.labels" $ | nindent 6 }}
      app.kubernetes.io/component: worker
{{- end }}
