{{- with .Values.autoscaling.worker }}
{{- if .enabled -}}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ printf "%s-%s" (include "authentik.names.fullname" $) "worker" }}
  labels:
    {{- include "authentik.labels" $ | nindent 4 }}
    app.kubernetes.io/component: "worker"
  {{- if $.Values.annotations }}
  annotations:
    {{- toYaml $.Values.annotations | nindent 4 }}
  {{- end }}
spec:
  minReplicas: {{ .minReplicas }}
  maxReplicas: {{ .maxReplicas }}
  metrics:
  - resource:
      name: cpu
      target:
        averageUtilization: {{ .targetCPUUtilizationPercentage }}
        type: Utilization
    type: Resource
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ printf "%s-%s" (include "authentik.names.fullname" $) "worker" }}
{{- end }}
{{- end }}
