{{- if and .Values.worker.enabled .Values.worker.metrics.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "authentik.worker.fullname" . }}-metrics
  namespace: {{ include "authentik.namespace" . | quote }}
  labels:
    {{- include "authentik.labels" (dict "context" . "component" (printf "%s-metrics" .Values.worker.name)) | nindent 4 }}
    {{- with .Values.worker.metrics.service.labels }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- if or .Values.worker.metrics.service.annotations .Values.global.addPrometheusAnnotations }}
  annotations:
    {{- if .Values.global.addPrometheusAnnotations }}
    prometheus.io/port: {{ .Values.worker.metrics.service.servicePort | quote }}
    prometheus.io/scrape: "true"
    {{- end }}
    {{- range $key, $value := .Values.worker.metrics.service.annotations }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
  {{- end }}
spec:
  type: {{ .Values.worker.metrics.service.type }}
  {{- if and .Values.worker.metrics.service.clusterIP (eq .Values.worker.metrics.service.type "ClusterIP") }}
  clusterIP: {{ .Values.worker.metrics.service.clusterIP }}
  {{- end }}
  ports:
  - name: {{ .Values.worker.metrics.service.portName }}
    protocol: TCP
    port: {{ .Values.worker.metrics.service.servicePort }}
    targetPort: metrics
  selector:
    {{- include "authentik.selectorLabels" (dict "context" . "component" .Values.worker.name) | nindent 4 }}
{{- end }}
