---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "authentik-remote-cluster.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "authentik-remote-cluster.labels" . | nindent 4 }}
  {{- with .Values.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "authentik-remote-cluster.fullname" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "authentik-remote-cluster.fullname" . }}
    namespace: {{ .Release.Namespace }}
